spring.application.name=payment

server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/paymentgateway
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

razorpay.key.id=rzp_test_TkUmdYoan6fvNb
razorpay.key.secret=0PVa2GswIJGKTsaueGlZV2uF
